name: ESLint

on:
  push:
    branches:
      - "**" # matches every branch
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - "**" # matches every branch
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          cache: "npm"
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
